### ISSUE TITLE
Project not fetching with OS 1.30

### ISSUE THREAD

**Issue by lamainrouge2** [mzero/elk-herd-project#17] opened 2021-07-26 09:22 UTC
Hi !
Just made the update to DT OS 1.30 and my projects are not fetching anymore :(
This update looks very important with lots of changes, I hope that it's only something I've done wrong and that I will find the right settings but I have been trying for two days and kind of desperate right now ...
I would be SO HAPPY if anyone can help me to fix this !!!

1. manage your Digitakt - elk-herd is scanning the +Drive OK - download and upload samples is OK
2. click on "Project"
3. click on "Fetch Project"
4. "Fetching project from digitakt" bar is not moving - I have to close or refresh the window - nothing happens in the DT
5. tried both mode USB MIDI or MIDI+AUDIO - not working
6. tried to create a new project and fetch it - not working
7. tried to power cycle the machine, unplugged the connection, updating Chrome - not working

environnement :
 - elk-herd 3.0
 - OS 10.13.6 High Sierra
 - Chrome
 - DT OS 1.30

Thank you some much in advance for your help :)
Best
lamainrouge2

**Comment by jpkarvonen** [comment] 2021-08-10 16:33
@lamainrouge2 try out the beta: https://electric.kitchen/crunch/beta/elk-herd/

I had the same issue but it is resolved for me there now.

**Comment by lamainrouge2** [comment] 2021-08-18 11:23
> @lamainrouge2 try out the beta: https://electric.kitchen/crunch/beta/elk-herd/
> 
> I had the same issue but it is resolved for me there now.

Thank You, the beta is now supporting DT OS 1.30 and this is awesome :)
I'll buy you a beer indeed @mzero, please, master, great work !

**Comment by tkatigid** [comment] 2022-01-26 04:09
Hi Guys

I was also having this issue when I updated to the 1.30 digitakt update which the beta version has fixed however if I 
1) Save a project into my downloads folder from Elk on the computer then 
2) Load a new project I want to send it to on the digitakt 
3) Fetch the new project I want to send it to on Elk
4) Import the saved file into the new project on Elk and assign it to one of the pattern slots
when I send it back nothing happens? the send bar goes along like its uploading but the digitakt doesn't register anything?

Any thoughts help much appreciated

**Comment by tkatigid** [comment] 2022-01-27 22:46
Nevermind my Digitakt was in overbridge mode 
mzero thanks for the software buying you a beer right now!

**Comment by mpicard** [comment] 2022-05-30 13:08
I have the same issue but with version1.30B and v3 of elk-herd, anyone else?

in USB AUDIO-MIDI mode, can load the +Drive, etc.

I found a "workaround" you need to HIT PLAY first and let a pattern play in the project before it starts fetching it/ progress bar starts. Weird but okay

**Comment by jonathanleinola** [comment] 2022-10-01 10:30
I have the same issue with OS 1.40. Did not work with @mpicard workaround either.

**Comment by nkear003** [comment] 2022-10-02 13:29
I can confirm this not working in DT v1.40 as well, none of the solutions in this thread worked. Using the beta link has previously worked for me with 1.30.

**Comment by Trolleydash** [comment] 2023-05-16 12:11
Hi you guys,

Same issue here, running up-to-date browsers and Digitakt v1.5. Seems to be a recurring issue with updates. Have tried the workarounds in the thread but none of them seem to be working. Any ideas/updates? 

Thanks everyone!
R

**Comment by mzero** [comment] 2024-05-22 18:18
Latest beta (as in yesterday!) now supports from 1.30 through 1.51A.
See here for running the beta:

https://www.elektronauts.com/t/elk-herd-3-2-beta-for-digitakt-os-1-51a-and-earlier/184908

I expect this to go mainline in two weeks at most.

**Closed as completed by mzero** 2024-05-22 18:18 UTC
Labels: bug, incoming
